### ISSUE TITLE
Relation/differences to h3, nitro, and hono

### ISSUE THREAD

**Issue by septatrix** [h3js/srvx#11]
### Describe the change

I found this but it's not clear to me how this relates to h3 and nitro. Is it completely independent, can they be used together...?

I also saw hono in the dependencies. Does it only use it for the nodejs compatibility layer? In general it would be good to state how this differs from hono

### Additional information

- [ ] Would you be willing to help?

**Comment by pi0** [comment]
devDependnecies are for benchmark purposesd. srvx is a low-level and fully independent library.

I plan to use srvx as a new bases for h3 v2, so if you are using h3 or nitro or nuxt, you don't need to use it directly.

It is partially [written here](https://srvx.pages.dev/guide/why#how-is-it-different).
